vkassharma59/pharmVetPat

src/app/components/header/header.component.html, src/app/components/header/header.component.scss, src/app/components/header/header.component.ts, src/app/components/results-common/chemi-tracker/chemi-tracker.component.ts, src/app/components/results-common/impurity/impurity.component.ts
=> Merge himanshi/fixes-1 into Q1/Release01

src/app/commons/navbar/navbar.component.html, src/app/components/home/home.component.html, src/app/components/pharma-database-search/pharma-database-search.component.html
made ui changes in home page and header
=> Updated header and home

src/app/commons/models/app-config.interface.ts, src/app/components/pharma-database-search/pharma-database-search.component.css, src/app/components/results-common/active-patent-card/active-patent-card.component.html, src/app/components/results-common/active-patent-card/active-patent-card.component.spec.ts, src/app/components/results-common/active-patent-card/active-patent-card.component.ts, src/app/components/results-common/active-patent/active-patent.component.html, src/app/components/results-common/active-patent/active-patent.component.ts, src/app/components/results-common/exim/exim.component.css, src/app/components/results-common/exim/exim.component.html, src/app/components/search-results/search-results.component.ts, src/app/config/app-config.ts, src/app/services/main-search/main-search.service.ts, src/assets/styles/text_style.scss
=> Data table changes

src/app/components/results-common/exim/exim.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.css, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/scientific-docs/scientific-docs.component.html
working on the scientificdoc tab filter
=> working on scientificdoc tab filter

src/app/commons/models/app-config.interface.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.html, src/app/components/results-common/gppd-db-card/gppd-db-card.component.spec.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.html, src/app/components/results-common/gppd-db/gppd-db.component.spec.ts, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.css, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.css, src/app/components/results-common/spcdb-card/spcdb-card.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/results-common/spcdb/spcdb.component.html, src/app/components/results-common/spcdb/spcdb.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts, src/app/components/search-results/search-results.component.ts, src/app/config/app-config.ts, src/app/services/main-search/main-search.service.ts
working on spcdb tab 
add the api
=> working on spcdb tab  add the api

src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/search-results/search-results.component.ts
working on the filter form for a particular column scientific-doc tab.
=> working on filter form  particular column

src/app/commons/child-paging/child-paging.component.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.html, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.html, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/search-results/search-results.component.ts, src/app/services/child-pagination/service-child-pagination.service.ts, src/app/services/main-search/main-search.service.ts
=> working on gppdDb tab

src/app/commons/child-paging/child-paging.component.ts, src/app/commons/child-pagning-table/child-pagning-table.component.html, src/app/commons/child-pagning-table/child-pagning-table.component.spec.ts, src/app/commons/child-pagning-table/child-pagning-table.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.html, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/scientific-docs/scientific-docs.component.html, src/app/components/results-common/scientific-docs/scientific-docs.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/results-common/spcdb/spcdb.component.css, src/app/components/results-common/spcdb/spcdb.component.html, src/app/components/results-common/spcdb/spcdb.component.ts
Add the global search  or working on order by search .
=> add the global search

src/app/commons/child-pagning-table/child-pagning-table.component.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.html, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/scientific-docs/scientific-docs.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/results-common/spcdb/spcdb.component.ts
Add the order by search in all tabs.
=> order by search 

src/app/commons/child-pagning-table/child-pagning-table.component.ts, src/app/components/results-common/active-patent-card/active-patent-card.component.ts, src/app/components/results-common/chemical-directory/chemical-directory.component.html, src/app/components/results-common/chemical-directory/chemical-directory.component.ts, src/app/components/results-common/exim-card/exim-card.component.ts, src/app/components/results-common/exim/exim.component.css, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/non-patent-card/non-patent-card.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/search-results/search-results.component.ts
Set the dynamic limit in the excel or CSV data download button.
=> set the dynamic limit in excel or csv data

src/app/commons/models/app-config.interface.ts, src/app/components/results-common/active-patent-card/active-patent-card.component.ts, src/app/components/results-common/exim-card/exim-card.component.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/non-patent-card/non-patent-card.component.ts, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/results-common/veterinary-us-approval-card/veterinary-us-approval-card.component.css, src/app/components/results-common/veterinary-us-approval-card/veterinary-us-approval-card.component.html, src/app/components/results-common/veterinary-us-approval-card/veterinary-us-approval-card.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/search-results/search-results.component.ts, src/app/config/app-config.ts, src/app/services/user_priviledges/user-priviledge.service.ts
ui green book or add the validation in download button spcd tab
=> ui green book or add the validation in download button spcd tab

src/app/commons/child-paging/child-paging.component.html, src/app/commons/child-paging/child-paging.component.ts, src/app/commons/child-pagning-table/child-pagning-table.component.css, src/app/commons/child-pagning-table/child-pagning-table.component.html, src/app/commons/child-pagning-table/child-pagning-table.component.ts, src/app/components/results-common/basic-route-card/basic-route-card.component.ts, src/app/components/results-common/veterinary-us-approval/veterinary-us-approval.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts
=> table pagination

src/app/components/pharma-database-search/pharma-database-search.component.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts
Add the condition back and the query button
=> add condition back and  query button

src/app/components/pharma-database-search/pharma-database-search.component.html, src/app/components/pharma-database-search/pharma-database-search.component.ts, src/app/components/results-common/canada-health/canada-health.component.css, src/app/components/results-common/canada-health/canada-health.component.html, src/app/components/results-common/europe-approval-card/europe-approval-card.component.css, src/app/components/results-common/europe-approval-card/europe-approval-card.component.html
UI changes Canada approval tab, EMA tab, and suggestion keyword home
=> UI changes canada approval tab, EMA tab,suggestion keyword home

src/app/commons/image-modal/image-modal.component.css, src/app/commons/image-modal/image-modal.component.html, src/app/commons/image-modal/image-modal.component.ts, src/app/commons/result-tab/result-tab.component.css, src/app/components/results-common/chemi-tracker-card/chemi-tracker-card.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.html, src/app/components/results-common/impurity-card/impurity-card.component.ts, src/app/components/results-common/technical-routes-card/technical-routes-card.component.ts, src/app/components/results-common/us-approval-card/us-approval-card.component.ts, src/assets/styles/_global_style.scss
=> correct the image size issue

src/app/components/results-common/active-patent/active-patent.component.html, src/app/components/results-common/active-patent/active-patent.component.ts, src/app/components/results-common/canada/canada.component.ts, src/app/components/results-common/dmf-card/dmf-card.component.html, src/app/components/results-common/dmf-card/dmf-card.component.ts, src/app/components/results-common/dmf/dmf.component.html, src/app/components/results-common/dmf/dmf.component.ts, src/app/components/results-common/exim/exim.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/imp/imp.component.ts, src/app/components/results-common/non-patent/non-patent.component.html, src/app/components/results-common/non-patent/non-patent.component.ts, src/app/components/results-common/us-approval-card/us-approval-card.component.html, src/app/components/route-result/route-result.component.ts
worked on the filter active patent DMF ,orange book UI changes.
=> worked on the filter active patent DMF ,orange book UI changes

src/app/components/pharma-database-search/pharma-database-search.component.ts, src/app/components/results-common/dmf-card/dmf-card.component.html, src/app/components/results-common/dmf-card/dmf-card.component.ts, src/app/components/results-common/dmf/dmf.component.html, src/app/components/results-common/dmf/dmf.component.ts, src/app/components/results-common/technical-routes-card/technical-routes-card.component.html, src/app/components/results-common/technical-routes-card/technical-routes-card.component.ts, src/app/components/results-common/technical-routes/technical-routes.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts
worked on dmf tab(show counrty)and also single download pdf( pending )
=> worked on dmf tab(show counrty)and also pdf

src/app/components/pharma-database-search/pharma-database-search.component.html, src/app/components/pharma-database-search/pharma-database-search.component.ts
=> search input

src/app/commons/child-paging/child-paging.component.ts, src/app/commons/child-pagning-table/child-pagning-table.component.ts, src/app/components/results-common/active-patent/active-patent.component.ts, src/app/components/results-common/basic-route-card/basic-route-card.component.html, src/app/components/results-common/basic-route-card/basic-route-card.component.ts, src/app/components/results-common/canada-health/canada-health.component.html, src/app/components/results-common/chemi-tracker-card/chemi-tracker-card.component.ts, src/app/components/results-common/chemi-tracker/chemi-tracker.component.ts, src/app/components/results-common/dmf-card/dmf-card.component.ts, src/app/components/results-common/dmf/dmf.component.html, src/app/components/results-common/dmf/dmf.component.ts, src/app/components/results-common/europe-approval/europe-approval.component.ts, src/app/components/results-common/exim/exim.component.ts, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/gppd-db/gppd-db.component.html, src/app/components/results-common/gppd-db/gppd-db.component.ts, src/app/components/results-common/non-patent/non-patent.component.ts, src/app/components/results-common/spcdb/spcdb.component.css, src/app/components/results-common/spcdb/spcdb.component.html, src/app/components/results-common/spcdb/spcdb.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/search-results/search-results.component.ts
Solve the issue table pagination or add the spcd filter ui, product info tab (|n) issue
=> table pagination ,spcd tab ,product info i

src/app/components/results-common/canada/canada.component.ts, src/app/components/results-common/dmf/dmf.component.html, src/app/components/results-common/dmf/dmf.component.ts, src/app/components/results-common/impurity/impurity.component.ts, src/app/components/results-common/indian-medicine-card/indian-medicine-card.component.html, src/app/components/results-common/indian-medicine-card/indian-medicine-card.component.ts, src/app/components/results-common/veterinary-us-approval/veterinary-us-approval.component.html, src/app/components/results-common/veterinary-us-approval/veterinary-us-approval.component.ts, src/app/config/app-config.ts
solve dmf data issue ,green book filter
=> solve dmf data issue ,green book filter

src/app/commons/child-paging/child-paging.component.ts, src/app/commons/result-tab/result-tab.component.ts, src/app/components/results-common/active-patent-card/active-patent-card.component.html, src/app/components/results-common/active-patent-card/active-patent-card.component.ts, src/app/components/results-common/exim-card/exim-card.component.html, src/app/components/results-common/exim-card/exim-card.component.ts, src/app/components/results-common/impurity-card/impurity-card.component.html, src/app/components/results-common/non-patent-card/non-patent-card.component.html, src/app/components/results-common/non-patent-card/non-patent-card.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts, src/app/components/search-results/search-results.component.html
correct pagination on click next button ,
add download condition show msg ,
add the clear filter condition all table
=> correct pagnation ,add download condition show msg ,add the clear filter condition all table

src/app/components/results-common/active-patent-card/active-patent-card.component.ts, src/app/components/results-common/active-patent/active-patent.component.css, src/app/components/results-common/active-patent/active-patent.component.html, src/app/components/results-common/active-patent/active-patent.component.ts
=> updated ui for active patent

src/app/components/pharma-database-search/pharma-database-search.component.ts, src/app/components/results-common/basic-route-card/basic-route-card.component.html, src/app/components/results-common/japan/japan.component.css, src/app/components/results-common/japan/japan.component.html, src/app/components/results-common/japan/japan.component.ts, src/app/components/route-result/route-result.component.css, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts, src/app/shared-ros.service.ts
header part changes , add the japan filter ui
=> header part changes,add the japan filter ui

src/app/components/results-common/imp-patents-card/imp-patents-card.component.html, src/app/components/results-common/imp-patents-card/imp-patents-card.component.ts, src/app/components/results-common/indian-medicine-card/indian-medicine-card.component.css, src/app/components/results-common/indian-medicine-card/indian-medicine-card.component.html, src/app/components/results-common/indian-medicine-card/indian-medicine-card.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/search-results/search-results.component.html
ui changes indian medicine tab
=> ui changes indian medicine tab

src/app/components/results-common/active-patent-card/active-patent-card.component.css, src/app/components/results-common/active-patent-card/active-patent-card.component.html, src/app/components/results-common/exim-card/exim-card.component.css, src/app/components/results-common/gppd-db-card/gppd-db-card.component.html, src/app/components/results-common/gppd-db/gppd-db.component.css, src/app/components/results-common/non-patent-card/non-patent-card.component.css, src/app/components/results-common/non-patent-card/non-patent-card.component.html, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.html, src/app/components/results-common/scientific-docs-card/scientific-docs-card.component.ts, src/app/components/results-common/spcdb-card/spcdb-card.component.css, src/app/components/results-common/spcdb-card/spcdb-card.component.html, src/app/components/route-result/route-result.component.html, src/app/components/search-results/search-results.component.ts
scientific UI , table dynamic width
=> scientific UI , table dynamic width

src/app/commons/pagination/pagination.component.ts, src/app/components/results-common/canada/canada.component.html, src/app/components/results-common/chemi-tracker/chemi-tracker.component.html, src/app/components/results-common/chemical-directory-card/chemical-directory-data-card.component.ts, src/app/components/results-common/chemical-directory/chemical-directory.component.html, src/app/components/results-common/dmf/dmf.component.html, src/app/components/results-common/europe-approval-card/europe-approval-card.component.ts, src/app/components/results-common/europe-approval/europe-approval.component.html, src/app/components/results-common/gppd-db-card/gppd-db-card.component.ts, src/app/components/results-common/imp/imp.component.html, src/app/components/results-common/impurity/impurity.component.html, src/app/components/results-common/indian/indian.component.html, src/app/components/results-common/japan/japan.component.html, src/app/components/results-common/korea/korea.component.html, src/app/components/results-common/litigation/litigation.component.html, src/app/components/results-common/scientific-docs/scientific-docs.component.html, src/app/components/results-common/spcdb-card/spcdb-card.component.ts, src/app/components/results-common/technical-routes/technical-routes.component.html, src/app/components/results-common/us-approval-card/us-approval-card.component.html, src/app/components/results-common/us-approval-card/us-approval-card.component.ts, src/app/components/results-common/us/us.component.html, src/app/components/results-common/veterinary-us-approval/veterinary-us-approval.component.html, src/app/components/route-result/route-result.component.html
pagenation main page ,hide and show table data orange book,chemi direct,ema
=> pagenation main page ,hide and show table data orange book ,chemi direct, ema

src/app/components/results-common/technical-routes-card/technical-routes-card.component.ts, src/app/components/route-result/route-result.component.ts
solve navigation issue,techincalpdf download button
=> solve navigation issue,techincalpdf download button

src/app/components/results-common/purple-book-card/purple-book-card.component.html, src/app/components/results-common/purple-book-card/purple-book-card.component.ts, src/app/components/results-common/purple-book/purple-book.component.html, src/app/components/results-common/purple-book/purple-book.component.ts, src/app/components/search-results/search-results.component.ts, src/app/config/app-config.ts
add the purple book api or link in patent number
=> add the purple book api or link in patent number

src/app/components/route-result/route-result.component.ts
=> add the purple book pdf

src/app/components/results-common/exim/exim.component.html, src/app/components/results-common/purple-book-card/purple-book-card.component.html, src/app/components/results-common/purple-book-card/purple-book-card.component.ts, src/app/components/route-result/route-result.component.html, src/app/components/route-result/route-result.component.ts
pdf work for single download add the validation for both button, purple
book table changes
=> pdf work for single download add the validation for both button, purple book table changes
